export const CATEGORY_ADDED_MESSAGE = "KATEGORİ EKLENMİŞTİR."
export const CATEGORY_UPDATE_MESSAGE = "KATEGORİ GÜNCELLENMİŞTİR."
export const CATEGORY_DELETE_MESSAGE = "KATEGORİ SİLİNMİŞTİR."
export const AUTH_ERROR_MESSAGE = "Login Olmanız Gerekmektedir."
export const AUTH_FORBIDDEN_MESSAGE = "Bu İşlemi Yapmaya Yetkiniz Bulunmamaktadır"
export const CUSTOM_ERROR_MESSAGE = "ERR MESSAGE"